from __future__ import annotations

import argparse
import csv
import json
import re
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
PROJECT_DIR = BASE_DIR.parent
DATA_DIR = PROJECT_DIR / "data"
DEFAULT_CANDIDATES_CSV = DATA_DIR / "relation_candidates.csv"
DEFAULT_SENTENCES_CSV = DATA_DIR / "sentence_index.csv"
DEFAULT_OUTPUT_DIR = DATA_DIR / "validated"

WINDOW_SIZE = 2
DEFAULT_THRESHOLD = 0.58

TOKEN_PATTERN = re.compile(r"[a-z0-9]+")
GAS_TERMS = {
    "air",
    "argon",
    "helium",
    "nitrogen",
    "oxygen",
    "co2",
    "n2",
    "o2",
    "n2o",
    "gas",
    "mixture",
    "admixture",
    "water",
}
GENERIC_MENTION_TERMS = {
    "observed",
    "measured",
    "results",
    "data",
    "result",
    "study",
    "model",
    "experiment",
    "experiments",
    "modelling",
}

PREDICATE_CUES = {
    "investigates": {"investigate", "investigated", "study", "studied", "impact", "effect", "observe", "observed", "transition", "analysis"},
    "usesDevice_Device_measures": {"using", "used", "diagnostic", "diagnostics", "measured", "measurements", "monitor", "detection", "spectroscopy"},
    "hasPlasmaSource": {"discharge", "dbd", "plasma", "source", "barrier"},
    "hasMedium": {"in", "with", "mixture", "gas", "admixture", "air", "argon", "helium", "nitrogen", "oxygen", "water"},
    "measures": {"measure", "measured", "measures", "diagnostic", "current", "voltage", "pressure", "temperature", "density", "intensity"},
    "usesConfiguration": {"configuration", "geometry", "setup", "arrangement", "electrode", "powered", "grounded"},
    "hasConfiguration": {"configuration", "geometry", "setup", "arrangement"},
    "generated by": {"generated", "produced", "formed", "created"},
    "generates": {"generates", "generated", "produces", "produced", "forms", "formed"},
    "hasApplicationField": {"application", "used", "for", "treatment", "etching", "medicine", "processing"},
    "usedToDiagnose_MaterialEntity_hasApplicationField": {"diagnose", "diagnostic", "application", "used"},
    "usedIn_ResearchActivity_investigates": {"investigate", "studied", "observed", "using", "used"},
    "usedIn_ResearchActivity_hasPlasmaSource": {"using", "used", "discharge", "source", "plasma"},
    "usedIn_ResearchActivity_hasMedium": {"using", "used", "in", "with", "mixture", "gas"},
    "hasPlasmaSource_generates": {"generates", "generated", "produces", "produced", "plasma"},
    "generatedBy_measures": {"generated", "measured", "measurement"},
    "measures_hasUnit": {"ns", "kv", "v", "ppm", "pa", "mhz", "khz", "cm", "mm", "s", "ms", "us"},
    "[Quantitative Descriptor] has [Unit]": {"ns", "kv", "v", "ppm", "pa", "mhz", "khz", "cm", "mm", "s", "ms", "us"},
    "unit of": {"ns", "kv", "v", "ppm", "pa", "mhz", "khz", "cm", "mm", "s", "ms", "us"},
}

UNIT_LIKE_TOKENS = {"ns", "kv", "v", "ppm", "pa", "mhz", "khz", "hz", "cm", "mm", "mbar", "k", "ev", "s", "ms", "us", "ps"}


@dataclass(frozen=True)
class ValidatedCandidate:
    candidate_id: str
    paper_id: str
    paper_title: str
    doi: str
    sentence_id: str
    sentence_index: int
    subject_text: str
    subject_type: str
    predicate: str
    object_text: str
    object_type: str
    relation_origin: str
    inherited_from: str | None
    confidence: float
    accepted: bool
    support_scope: str
    support_sentence_ids: str
    support_sentence_count: int
    evidence_text: str
    context_text: str
    score_breakdown: str


@dataclass(frozen=True)
class ValidatedRelation:
    relation_id: str
    paper_id: str
    paper_title: str
    doi: str
    subject_text: str
    subject_type: str
    predicate: str
    object_text: str
    object_type: str
    best_confidence: float
    support_count: int
    support_sentence_ids: str
    support_scope: str
    representative_evidence: str
    relation_origin: str
    inherited_from: str | None


def tokenize(text: str) -> list[str]:
    return TOKEN_PATTERN.findall((text or "").casefold())


def normalized_text(text: str) -> str:
    return " ".join(tokenize(text))


def load_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def build_sentence_lookup(
    sentences: list[dict[str, str]],
) -> tuple[dict[str, dict[str, str]], dict[str, dict[int, dict[str, str]]]]:
    by_id = {row["sentence_id"]: row for row in sentences}
    by_paper: dict[str, dict[int, dict[str, str]]] = defaultdict(dict)
    for row in sentences:
        by_paper[row["paper_id"]][int(row["sentence_index"])] = row
    return by_id, by_paper


def get_context_window(
    sentence_row: dict[str, str],
    sentences_by_paper: dict[str, dict[int, dict[str, str]]],
    window_size: int,
) -> list[dict[str, str]]:
    paper_id = sentence_row["paper_id"]
    sentence_index = int(sentence_row["sentence_index"])
    paper_sentences = sentences_by_paper[paper_id]
    rows = []
    for idx in range(sentence_index - window_size, sentence_index + window_size + 1):
        if idx in paper_sentences:
            rows.append(paper_sentences[idx])
    return rows


def mention_quality(text: str) -> tuple[float, list[str]]:
    notes: list[str] = []
    score = 0.0
    tokens = tokenize(text)
    clean = normalized_text(text)

    if len(tokens) >= 2:
        score += 0.07
        notes.append("multi_token_mention")
    elif len(tokens) == 1:
        score += 0.01
        notes.append("single_token_mention")

    if clean in GENERIC_MENTION_TERMS:
        score -= 0.18
        notes.append("generic_mention_penalty")

    if text.endswith("."):
        score -= 0.08
        notes.append("terminal_punctuation_penalty")

    if len(clean) <= 2 and clean not in UNIT_LIKE_TOKENS:
        score -= 0.12
        notes.append("very_short_mention_penalty")

    return score, notes


def predicate_specific_adjustment(
    candidate: dict[str, str],
    context_tokens: set[str],
    breakdown: list[str],
) -> tuple[float, bool]:
    predicate = candidate["predicate"]
    score = 0.0
    anchored = False

    cues = PREDICATE_CUES.get(predicate, set())
    cue_hits = sorted(cues & context_tokens)
    if cue_hits:
        score += 0.14
        anchored = True
        breakdown.append(f"predicate_cues:{'|'.join(cue_hits[:4])}")

    object_tokens = set(tokenize(candidate["object_text"]))
    subject_tokens = set(tokenize(candidate["subject_text"]))

    if predicate == "hasMedium" and object_tokens & GAS_TERMS:
        score += 0.18
        anchored = True
        breakdown.append("medium_like_object_bonus")

    if predicate in {"[Quantitative Descriptor] has [Unit]", "unit of", "measures_hasUnit"}:
        if object_tokens & UNIT_LIKE_TOKENS or subject_tokens & UNIT_LIKE_TOKENS:
            score += 0.24
            anchored = True
            breakdown.append("unit_pattern_bonus")

    if predicate == "hasPlasmaSource" and {"discharge", "dbd", "plasma"} & object_tokens:
        score += 0.18
        anchored = True
        breakdown.append("plasma_source_object_bonus")

    if predicate == "usesConfiguration" and {"configuration", "geometry", "electrode", "setup"} & object_tokens:
        score += 0.18
        anchored = True
        breakdown.append("configuration_object_bonus")

    if predicate in {"usesDevice_Device_measures", "measures"} and {"measure", "measured", "diagnostic", "diagnostics"} & context_tokens:
        score += 0.14
        anchored = True
        breakdown.append("measurement_context_bonus")

    if predicate == "hasMedium" and "pressure" in object_tokens:
        score -= 0.18
        breakdown.append("pressure_as_medium_penalty")

    if predicate in {"involves_MaterialEntity_hasProperty", "hasProperty"} and "pressure" in object_tokens:
        score -= 0.15
        breakdown.append("pressure_as_property_penalty")

    return score, anchored


def validate_candidate(
    candidate: dict[str, str],
    sentence_row: dict[str, str],
    context_rows: list[dict[str, str]],
    threshold: float,
) -> ValidatedCandidate:
    evidence_text = sentence_row["text"]
    context_text = " ".join(row["text"] for row in context_rows)
    evidence_tokens = set(tokenize(evidence_text))
    context_tokens = set(tokenize(context_text))

    subject_norm = normalized_text(candidate["subject_text"])
    object_norm = normalized_text(candidate["object_text"])

    breakdown: list[str] = []
    score = 0.2
    breakdown.append("base_same_sentence=0.2")

    if subject_norm and subject_norm in normalized_text(evidence_text):
        score += 0.1
        breakdown.append("subject_in_evidence=0.1")
    elif subject_norm and subject_norm in normalized_text(context_text):
        score += 0.04
        breakdown.append("subject_in_context=0.04")

    if object_norm and object_norm in normalized_text(evidence_text):
        score += 0.1
        breakdown.append("object_in_evidence=0.1")
    elif object_norm and object_norm in normalized_text(context_text):
        score += 0.04
        breakdown.append("object_in_context=0.04")

    subject_quality, subject_notes = mention_quality(candidate["subject_text"])
    object_quality, object_notes = mention_quality(candidate["object_text"])
    score += subject_quality + object_quality
    breakdown.extend(subject_notes)
    breakdown.extend(object_notes)

    if int(candidate["sentence_id"].split(":s")[-1]) != int(sentence_row["sentence_index"]):
        breakdown.append("sentence_index_mismatch")

    predicate_bonus, has_anchor = predicate_specific_adjustment(candidate, context_tokens, breakdown)
    score += predicate_bonus

    if not (set(tokenize(candidate["subject_text"])) & evidence_tokens):
        score -= 0.08
        breakdown.append("subject_not_token_supported_penalty")
    if not (set(tokenize(candidate["object_text"])) & evidence_tokens):
        score -= 0.08
        breakdown.append("object_not_token_supported_penalty")

    support_ids = [row["sentence_id"] for row in context_rows]
    support_scope = "neighbor_window" if len(context_rows) > 1 else "same_sentence"
    if len(context_rows) > 1 and has_anchor:
        score += 0.03
        breakdown.append("neighbor_window_with_anchor=0.03")

    if not has_anchor:
        score -= 0.16
        breakdown.append("missing_predicate_anchor_penalty")

    confidence = max(0.0, min(1.0, round(score, 4)))
    accepted = confidence >= threshold and has_anchor

    return ValidatedCandidate(
        candidate_id=candidate["candidate_id"],
        paper_id=candidate["paper_id"],
        paper_title=candidate["paper_title"],
        doi=candidate["doi"],
        sentence_id=candidate["sentence_id"],
        sentence_index=int(sentence_row["sentence_index"]),
        subject_text=candidate["subject_text"],
        subject_type=candidate["subject_type"],
        predicate=candidate["predicate"],
        object_text=candidate["object_text"],
        object_type=candidate["object_type"],
        relation_origin=candidate["relation_origin"],
        inherited_from=candidate["inherited_from"] or None,
        confidence=confidence,
        accepted=accepted,
        support_scope=support_scope,
        support_sentence_ids=";".join(support_ids),
        support_sentence_count=len(support_ids),
        evidence_text=evidence_text,
        context_text=context_text,
        score_breakdown=" | ".join(breakdown),
    )


def consolidate_relations(validated: list[ValidatedCandidate]) -> list[ValidatedRelation]:
    grouped: dict[tuple[str, str, str, str, str, str], list[ValidatedCandidate]] = defaultdict(list)
    for row in validated:
        if not row.accepted:
            continue
        key = (
            row.paper_id,
            row.subject_text,
            row.subject_type,
            row.predicate,
            row.object_text,
            row.object_type,
        )
        grouped[key].append(row)

    relations: list[ValidatedRelation] = []
    for index, rows in enumerate(grouped.values(), start=1):
        best = max(rows, key=lambda item: item.confidence)
        support_ids = sorted({sid for row in rows for sid in row.support_sentence_ids.split(";") if sid})
        scopes = sorted({row.support_scope for row in rows})
        relations.append(
            ValidatedRelation(
                relation_id=f"rel_{index:06d}",
                paper_id=best.paper_id,
                paper_title=best.paper_title,
                doi=best.doi,
                subject_text=best.subject_text,
                subject_type=best.subject_type,
                predicate=best.predicate,
                object_text=best.object_text,
                object_type=best.object_type,
                best_confidence=best.confidence,
                support_count=len(rows),
                support_sentence_ids=";".join(support_ids),
                support_scope=";".join(scopes),
                representative_evidence=best.evidence_text,
                relation_origin=best.relation_origin,
                inherited_from=best.inherited_from,
            )
        )
    return relations


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate KG relation candidates using sentence and neighboring-sentence context."
    )
    parser.add_argument(
        "--candidates-csv",
        type=Path,
        default=DEFAULT_CANDIDATES_CSV,
        help=f"Input relation candidate CSV. Default: {DEFAULT_CANDIDATES_CSV}",
    )
    parser.add_argument(
        "--sentences-csv",
        type=Path,
        default=DEFAULT_SENTENCES_CSV,
        help=f"Input sentence index CSV. Default: {DEFAULT_SENTENCES_CSV}",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Directory for validated outputs. Default: {DEFAULT_OUTPUT_DIR}",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=DEFAULT_THRESHOLD,
        help=f"Acceptance threshold between 0 and 1. Default: {DEFAULT_THRESHOLD}",
    )
    parser.add_argument(
        "--window-size",
        type=int,
        default=WINDOW_SIZE,
        help=f"Neighboring sentence window on each side. Default: {WINDOW_SIZE}",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    candidates = load_csv(args.candidates_csv)
    sentences = load_csv(args.sentences_csv)
    sentence_by_id, sentences_by_paper = build_sentence_lookup(sentences)

    validated_rows: list[ValidatedCandidate] = []
    for candidate in candidates:
        sentence_row = sentence_by_id[candidate["sentence_id"]]
        context_rows = get_context_window(sentence_row, sentences_by_paper, args.window_size)
        validated_rows.append(
            validate_candidate(candidate, sentence_row, context_rows, args.threshold)
        )

    consolidated = consolidate_relations(validated_rows)

    summary = {
        "candidate_count": len(validated_rows),
        "accepted_candidate_count": sum(1 for row in validated_rows if row.accepted),
        "accepted_relation_count": len(consolidated),
        "acceptance_rate": round(
            sum(1 for row in validated_rows if row.accepted) / len(validated_rows), 4
        ) if validated_rows else 0.0,
        "threshold": args.threshold,
        "window_size": args.window_size,
        "top_predicates_after_validation": Counter(
            row.predicate for row in validated_rows if row.accepted
        ).most_common(15),
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)
    write_csv(
        args.output_dir / "validated_relation_candidates.csv",
        [asdict(row) for row in validated_rows],
    )
    write_csv(
        args.output_dir / "validated_relations.csv",
        [asdict(row) for row in consolidated],
    )
    (args.output_dir / "validation_summary.json").write_text(
        json.dumps(summary, indent=2),
        encoding="utf-8",
    )

    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
